language: node_js
node_js:
  - "4.0"
addons:
  apt:
    packages:
      - xvfb
  firefox: "45.0"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - tar -xjf /tmp/firefox-45.0.tar.bz2 --directory /tmp
  - export PATH="/tmp/firefox:$PATH
  - echo "Using firefox version `firefox --version`
install:
  - npm install
script:
  - npm test
notifications:
  email: false
